version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql_container
    environment:
      - POSTGRESQL_USERNAME=barber
      - POSTGRESQL_PASSWORD=barber
      - POSTGRESQL_DATABASE=barbershop
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"

volumes:
  postgresql_data:
    driver: local
